// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $package_subject_ from "./routes/package/[subject].tsx";
import * as $home from "./islands/home.tsx";
import * as $listing from "./islands/listing.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
    "./routes/package/[subject].tsx": $package_subject_,
  },
  islands: {
    "./islands/home.tsx": $home,
    "./islands/listing.tsx": $listing,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
